"use strict";

const Promise = require("bluebird");
const request = require("request-promise");
const errors = require("request-promise/errors");

class CleverBotIO {

  /**
   * Constructor for the class.
   * @constructor
   * @param  {string}    user   The API user given to you by the keys page. https://cleverbot.io/keys
   * @param  {string}    key    The API key generated by the keys page.
   * @param  {string}    [nick] Optional nick to use. Could also be a nick from a previous session.
   */
  constructor(user, key, nick) {
    this.user = user;
    this.key = key;
    this.nick = nick || "";
    this.url = "https://cleverbot.io/1.0/";
  }

  /**
   * This method sets the nick.
   * @method setNick
   * @param  {string} nick The nick to use.
   */
  setNick(nick) {
    this.nick = nick;
  }

  /**
   * This method allows the setting of the URL to use for the API.
   * @method setURL
   * @param  {string} url The new API url.
   */
  setURL(url) {
    this.url = url;
  }

  /**
   * This method creates a session to use on the API. This should be called when you want to create a new session
   * and not when you have custom set a nick before calling the "ask" method.
   * @method create
   * @return {object} Response from the API.
   */
  create() {
    let that = this;
    return new Promise(function (resolve, reject) {
      that._request("POST", "create", {
        user: that.user,
        key: that.key,
        nick: that.nick
      }).then(function (res) {
        // Parse the response from the API.
        let response = JSON.parse(res.body);
        // Check to see if the request to create a bot session / nick was successful.
        if (response.status === "success") {
          that.nick = response.nick;
          resolve(response);
        }
        // Check to see if the API returned with an error about the nick being used already.
        if (response.status === "Error: reference name already exists") {
          reject("Error: reference name '" + that.nick +"' already exists");
        }
        // Reject the Promise if we get any other status from the API.
        reject(response);
      }).catch(errors.StatusCodeError, function (err) {
        if (err.statusCode === 404) {
          reject("API endpoints unreachable.");
        }
        reject(err);
      });
    });
  }

  /**
   * This method allows you to ask CleverBot something to get a response back.
   * @method ask
   * @param  {string} message The message / question to ask the bot.
   * @return {object}         Response from the API.
   */
  ask(message) {
    let that = this;
    return new Promise(function (resolve, reject) {
      that._request("POST", "ask", {
        user: that.user,
        key: that.key,
        nick: that.nick,
        text: message
      }).then(function (res) {
        // Parse the response from the API.
        let response = JSON.parse(res.body);
        // Check to see if the request to ask the API for a response was successful.
        if (response.status === "success") {
          resolve(response);
        }
        // Reject the Promise if we get any other status from the API.
        reject(response);
      }).catch(errors.StatusCodeError, function (err) {
        if (err.statusCode === 404) {
          reject("API endpoints unreachable.");
        }
        reject(err);
      });
    });
  }

  /**
   * This method handles any requests to the CleverBotIO API.
   * @method request
   * @param  {string} method   The method type for the request.
   * @param  {string} endpoint The endpoint to request too on the CleverBotIO API.
   * @param  {object} [data]   Any data to send in the request.
   * @return {*}               The request promise resolved / rejected method for the request.
   */
  _request(method, endpoint, data) {
    return request({
      method: method.toUpperCase(),
      url: this.url + endpoint,
      form: data,
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; CleverBotIO)"
      },
      resolveWithFullResponse: true
    });
  }
}

module.exports = CleverBotIO;
